#!/usr/bin/env python3
"""
rebuild-index.py — Rebuilds docs/skills-reference.md and docs/agents-reference.md
from the actual files in skills/ and agents/ directories.

Run: python3 scripts/rebuild-index.py
"""

import os
import re
from pathlib import Path
from datetime import datetime

REPO_ROOT = Path(__file__).parent.parent
SKILLS_DIR = REPO_ROOT / "skills"
AGENTS_DIR = REPO_ROOT / "agents"
DOCS_DIR = REPO_ROOT / "docs"
README = REPO_ROOT / "README.md"


def parse_skill_frontmatter(skill_path):
    """Parse SKILL.md frontmatter for name, description, triggers."""
    skill_md = skill_path / "SKILL.md"
    if not skill_md.exists():
        return None

    content = skill_md.read_text(errors="replace")
    name = skill_path.name

    # Extract description from frontmatter
    desc_match = re.search(r'^description:\s*["\']?(.*?)["\']?\s*$', content, re.MULTILINE)
    description = desc_match.group(1).strip() if desc_match else "—"
    if description in (">", "", "null"):
        # Try to get first non-header line as description
        lines = [l.strip() for l in content.split('\n') if l.strip() and not l.startswith('#') and not l.startswith('---') and not l.startswith('name:') and not l.startswith('description:')]
        description = lines[0][:100] if lines else "—"

    # Extract triggers
    trigger_match = re.search(r'(?:Triggers?|TRIGGERS?):\s*(.*?)(?:\n\n|\n#)', content, re.DOTALL)
    triggers = "—"
    if trigger_match:
        raw = trigger_match.group(1).strip().replace('\n', ' ')
        triggers = raw[:120] + "..." if len(raw) > 120 else raw

    return {
        "name": name,
        "description": description,
        "triggers": triggers,
    }


def get_agent_division(agent_name):
    """Determine agent division from name prefix."""
    prefixes = {
        "academic-": "Academic",
        "ads-": "Ads / Paid Media",
        "paid-media-": "Ads / Paid Media",
        "agency-": "Agency",
        "design-": "Design",
        "engineering-": "Engineering",
        "finance-": "Finance",
        "game-": "Game Development",
        "godot-": "Game Development",
        "roblox-": "Game Development",
        "unity-": "Game Development",
        "unreal-": "Game Development",
        "level-": "Game Development",
        "narrative-": "Game Development",
        "geo-": "GEO / SEO",
        "healthcare-": "Healthcare",
        "hr-": "HR / Recruitment",
        "recruitment-": "HR / Recruitment",
        "legal-": "Legal",
        "market-": "Marketing",
        "marketing-": "Marketing",
        "product-": "Product",
        "project-management-": "Project Management",
        "project-manager-": "Project Management",
        "sales-": "Sales",
        "specialized-": "Specialized",
        "support-": "Support / Operations",
        "testing-": "Testing / QA",
        "xr-": "XR / Spatial",
        "visionos-": "XR / Spatial",
    }
    for prefix, division in prefixes.items():
        if agent_name.startswith(prefix):
            return division
    return "Miscellaneous"


def rebuild_skills_reference():
    """Rebuild docs/skills-reference.md from skills/ directory."""
    skills = []
    for skill_dir in sorted(SKILLS_DIR.iterdir()):
        if skill_dir.is_dir():
            data = parse_skill_frontmatter(skill_dir)
            if data:
                skills.append(data)

    lines = [
        "# Skills Reference — All Skills",
        "",
        f"Auto-generated from `skills/` directory. Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "---",
        "",
        "| Skill | Description | Trigger Keywords |",
        "|---|---|---|",
    ]

    for s in skills:
        name = s["name"]
        desc = s["description"].replace("|", "\\|")
        triggers = s["triggers"].replace("|", "\\|")
        lines.append(f"| `{name}` | {desc} | {triggers} |")

    lines.extend([
        "",
        "---",
        "",
        f"*Total: {len(skills)} skills | Auto-generated by `scripts/rebuild-index.py`*",
    ])

    out = DOCS_DIR / "skills-reference.md"
    out.write_text("\n".join(lines))
    print(f"Rebuilt skills-reference.md — {len(skills)} skills")
    return len(skills)


def rebuild_agents_reference():
    """Rebuild docs/agents-reference.md from agents/ directory."""
    agents_by_division = {}

    for agent_file in sorted(AGENTS_DIR.iterdir()):
        if agent_file.suffix in (".md", ".yaml"):
            name = agent_file.stem
            division = get_agent_division(name)
            if division not in agents_by_division:
                agents_by_division[division] = []
            agents_by_division[division].append(name)

    lines = [
        "# Agents Reference — All Agents",
        "",
        f"Auto-generated from `agents/` directory. Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "---",
        "",
    ]

    total = 0
    for division in sorted(agents_by_division.keys()):
        agents = agents_by_division[division]
        lines.extend([
            f"## {division} Division ({len(agents)} agents)",
            "",
            "| Agent | Name |",
            "|---|---|",
        ])
        for agent in agents:
            display = agent.replace("-", " ").title()
            lines.append(f"| `{agent}` | {display} |")
        lines.append("")
        total += len(agents)

    lines.extend([
        "---",
        "",
        f"*Total: {total} agents | Auto-generated by `scripts/rebuild-index.py`*",
    ])

    out = DOCS_DIR / "agents-reference.md"
    out.write_text("\n".join(lines))
    print(f"Rebuilt agents-reference.md — {total} agents")
    return total


def update_readme_counts(skill_count, agent_count):
    """Update badge counts in README.md."""
    content = README.read_text()

    # Update Skills badge
    content = re.sub(
        r'!\[Skills\]\(https://img\.shields\.io/badge/Skills-\d+-',
        f'![Skills](https://img.shields.io/badge/Skills-{skill_count}-',
        content
    )

    # Update Agents badge
    content = re.sub(
        r'!\[Agents\]\(https://img\.shields\.io/badge/Agents-\d+-',
        f'![Agents](https://img.shields.io/badge/Agents-{agent_count}-',
        content
    )

    README.write_text(content)
    print(f"Updated README badges: {skill_count} skills, {agent_count} agents")


if __name__ == "__main__":
    print("Rebuilding index...")
    skill_count = rebuild_skills_reference()
    agent_count = rebuild_agents_reference()
    update_readme_counts(skill_count, agent_count)
    print("Done.")
